# top level stuff you probably don't need to touch
highlighter: rouge
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true

excerpt_separator: <!--more-->

# edit here to achieve your personal greatness
url: http://arialdomartini.github.io/
baseurl: /
title: Arialdo Martini
author: Arialdo Martini
description: Personal resume
avatar: arialdomartini.jpg
email: arialdo.martini@gmail.com
github: arialdomartini
twitter: arialdomartini
linkedin: https://it.linkedin.com/in/arialdomartini
stackoverflow: /users/202443/arialdo-martini
#Comment out if you don't want disqus 
#disqus: arialdomartini-github-io
analytics:
  provider: "google-gtag"
  google:
    measurement_id: G-DC68MMLW4T
    anonymize_ip: false


# needed for travis-ci build
#exclude: [vendor]
permalink: /:title
